# Generated by Django 4.2 on 2024-03-02 08:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=45, null=True, verbose_name='Marca')),
            ],
        ),
        migrations.CreateModel(
            name='Provedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prov', models.CharField(max_length=45, null=True, verbose_name='Proovedor')),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product/%Y/%m/%d', verbose_name='Imagen')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('pvp', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Precio de venta')),
                ('exist', models.IntegerField(default=0, verbose_name='Existencias')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de adquisición')),
                ('compra_pvp', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Precio de compra')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.marca', verbose_name='Marca')),
                ('provedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.provedor', verbose_name='Proovedor')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['id'],
            },
        ),
    ]
