# Generated by Django 4.2 on 2024-03-05 01:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=45, null=True, verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Provedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prov', models.CharField(max_length=45, null=True, verbose_name='Proovedor')),
            ],
            options={
                'verbose_name': 'Proovedor',
                'verbose_name_plural': 'Proovedores',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product/%Y/%m/%d', verbose_name='Imagen')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('pvp', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Precio de venta')),
                ('exist', models.IntegerField(default=0, verbose_name='Existencias')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de adquisición')),
                ('compra_pvp', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Precio de compra')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.marca', verbose_name='Marca')),
                ('provedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.provedor', verbose_name='Proovedor')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Clientes')),
                ('apellidos', models.CharField(max_length=150, verbose_name='Apellidos')),
                ('cel', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('mail', models.EmailField(max_length=254)),
                ('direc', models.CharField(blank=True, max_length=80, null=True, verbose_name='Dirección')),
                ('tel_empresa', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('nombre_empresa', models.CharField(blank=True, max_length=50, null=True, verbose_name='Empresa')),
                ('estado_deuda', models.CharField(choices=[('deuda', 'Deuda'), ('sin_deuda', 'Sin Deuda')], default='sin_deuda', max_length=9, verbose_name='Estado')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['id'],
            },
        ),
    ]
