# Generated by Django 4.2 on 2024-03-05 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='cel',
            field=models.CharField(max_length=50, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='tel_empresa',
            field=models.CharField(max_length=50, verbose_name='Telefono empresa'),
        ),
    ]
