# Generated by Django 4.2 on 2024-03-12 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_alter_clientes_cel_alter_clientes_tel_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='estado_deuda',
            field=models.CharField(choices=[('DEUDA', 'Deuda'), ('SIN DEUDA', 'Sin Deuda')], default='Sin Deuda', max_length=15, verbose_name='Estado'),
        ),
    ]
