# Generated by Django 4.2 on 2024-03-12 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_alter_clientes_estado_deuda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='estado_deuda',
            field=models.CharField(choices=[('DEUDA', 'Deuda'), ('SIN DEUDA', 'Sin Deuda')], default='SIN DEUDA', max_length=15, verbose_name='Estado'),
        ),
    ]
